# List of dependencies of the project

[versions]
coroutines = "1.8.0"          # https://github.com/Kotlin/kotlinx.coroutines/releases

[plugins]

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[bundles]
